name: Change ArgoCD Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_PIPELINE1 }}

      - name: Connect to AKS cluster
        run: |
          az aks get-credentials \
            --resource-group myResourceGroup-new \
            --name azuredevops \
            --overwrite-existing

      - name: Install helm chart
        uses: azure/setup-helm@v4
      - name: run helm install command
        run: |
          helm install demo ./nginx-app/chart1
